export const LOCATION_DATA: any = {
  hcm: {
    name: 'Hồ Chí Minh',
    districts: [
      'Tất cả Quận',
      'Quận 1',
      'Quận 3',
      'Quận 4',
      'Quận 5',
      'Quận 6',
      'Quận 7',
      'Quận 8',
      'Quận 10',
      'Quận 11',
      'Quận 12',
      'Bình Tân',
      'Bình Thạnh',
      'Gò Vấp',
      'Phú Nhuận',
      'Tân Bình',
      'Tân Phú',
      'Thủ Đức',
      'Bình Chánh',
      'Cần Giờ',
      'Củ Chi',
      'Hóc Môn',
      'Nhà Bè',
    ],
  },
  hn: {
    name: 'Hà Nội',
    districts: [
      'Tất cả Quận',
      'Ba Đình',
      'Hoàn Kiếm',
      'Tây Hồ',
      'Long Biên',
      'Cầu Giấy',
      'Đống Đa',
      'Hai Bà Trưng',
      'Hoàng Mai',
      'Thanh Xuân',
      'Hà Đông',
      'Bắc Từ Liêm',
      'Nam Từ Liêm',
      'Sơn Tây',
      'Ba Vì',
      'Chương Mỹ',
      'Đan Phượng',
      'Đông Anh',
      'Gia Lâm',
      'Hoài Đức',
      'Mê Linh',
      'Mỹ Đức',
      'Phú Xuyên',
      'Phúc Thọ',
      'Quốc Oai',
      'Sóc Sơn',
      'Thạch Thất',
      'Thanh Oai',
      'Thanh Trì',
      'Thường Tín',
      'Ứng Hòa',
    ],
  },
  dl: {
    name: 'Đắk Lắk',
    districts: ['TP. Buôn Ma Thuột'],
  },
};
